export const SALT_OR_ROUNDS = 10;

export const ACCESS_TOKEN_EXPIRY = 15 * 60 // 15m
export const REFRESH_TOKEN_EXPIRY = 7 * 24 * 60 * 60 // 7 DAYS

export const REFRESH_TOKEN_MAX_AGE = REFRESH_TOKEN_EXPIRY * 1000